### ISSUE TITLE
Run on startup?

### ISSUE THREAD

**Issue by tonymckendry** [Kr0ff/VMWare-Guest-FullScreen#2]
This is awesome and works great - I've been trying (and failing) to figure out a solution to run this automatically when I start my VM - any suggestions?

**Comment by Kr0ff** [comment]
Hey, you dont need to run it every time you boot your system. All necessary services will be enabled so they will start at boot time. ;) 

The vmware-user-suid-wrapper will be added to the very bottom of your i3 config file

**Comment by tonymckendry** [comment]
Thanks for the response, I'm obviously still learning. 

I am finding now that if I start my VM in fullscreen, that the resizing and everything works great - but if I start it in windowed mode (and even after killing X and starting it again with CTRL+ALT+F2) it does not behave correctly. Any idea why this might be?

**Comment by Kr0ff** [comment]
Im not sure why this could be it... i3 has less packages and is a barebones window manager, something like XFCE4, KDE, Gnome, Mate, etc those come with a lot more packages and thus make integration for auto screen resizing and resolution detection better.

It is possible to integrate i3 with a chosen desktop environment, i.e i3 + XFCE or i3 + KDE... You could potentially look into that if wish.

lastly, it might be possible that the necessary services dont start correctly...
